5 module solution
js-tasks-ru/jsbasic-20240808_vlada-protsenko pull request #4
Opened 2024-09-06 16:29 UTC by chevlada

2024-09-06 16:30 UTC, jsru-1 commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-09-08 15:15 UTC, SinimaWath requested changes
Тут все кр

2024-09-08 15:15 UTC, SinimaWath commented on 5-module/3-task/index.js
> +  arrowRight.addEventListener("click", function () {
Тут можно использовать стрелочные функции

2024-09-08 15:15 UTC, SinimaWath commented on 5-module/3-task/index.js
> +      }
Этот код повторяется 2 раза, можно вынести в общую функцию: `updateArrows` к примеру, чтобы его переиспользовать

2024-09-12 07:31 UTC, closed without merging